version: '2.1'
orbs:
  aws-ecr: circleci/aws-ecr@8.2.1
workflows:
  test_is_test:
    jobs:
      - aws-ecr/build-and-push-image:
          aws-access-key-id: AWS_ACCESS_KEY2
          aws-secret-access-key: AWS_SECRET_KEY2
          registry-id: AWS_REGISTRY_ID2
          region: ${AWS_REGION2}
          repo: 'sapphirestudios'
          tag: latest
      - runner-test:
          requires:
            - aws-ecr/build-and-push-image
        

jobs:
  
  runner-test:
    machine: true
    resource_class: tan0300/test2
    steps:
      - run:
          name: Deploy
          command: aws ecr get-login-password --region ${AWS_REGION2} | 
            docker login --username AWS --password-stdin ${AWS_REGISTRY_ID2}.dkr.ecr.${AWS_REGION2}.amazonaws.com | 
            docker pull ${AWS_REGISTRY_ID2}.dkr.ecr.${AWS_REGION2}.amazonaws.com/${AWS_REPO2}:latest |
            docker rm test-docker |
            docker run -p 3005:3005 --name="test-docker" -dit  ${AWS_REGISTRY_ID2}.dkr.ecr.${AWS_REGION2}.amazonaws.com/${AWS_REPO2}:latest


           