version: 2
orbs:
  aws-ecr: circleci/aws-ecr@7.0.0
workflows:
  push-to-ecr:
    jobs:
      - aws-ecr/build-and-push-image:
          aws-access-key-id: ${AWS_ACCESS_KEY}
          aws-secret-access-key: ${AWS_SECRET_KEY}
          region: ${AWS_REGION}
          repository: ${AWS_REPO}
          tag: latest