version: '2.1'
orbs:
  aws-ecr: circleci/aws-ecr@8.2.1
workflows:
  build_and_push_images:
    jobs:
      - checkout
      - aws-ecr/build-and-push-image:
          aws-access-key-id: AWS_ACCESS_KEY
          aws-secret-access-key: AWS_SECRET_KEY
          registry-id: AWS_REGISTRY_ID
          region: ${AWS_REGION}
          repo: 'test-jonathan'
          tag: latest
          assume-web-identity: true
      - run:
          name: Deploy
          command: |
            docker pull 144517920453.dkr.ecr.ap-southeast-1.amazonaws.com\test-jonathan

jobs:
  runner-test:
    machine: true
    resource_class: tan0300/test2
    steps:
      - run: ''